# -*- coding: utf-8 -*-
"""8_Ensamble_para_clasificacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-BMIp7sANlimeIfAGbU9CK3A2i4zluN

# Ensamble de Clasificadores
1. Preparación de datos
2. División de datos
3. Clasificadores individuales (débiles)
4. Bagging
5. Random Forest
6. Boosting
7. Votación "hard"
8. Votación "soft"
9. Stacking
10. Guardamos el mejor modelo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# 1. Preparación de datos"""

data = pd.read_excel("ataque_corazon.xlsx",sheet_name=0)
data.info()

data.head()

#Corrección tipos de datos
data['hypertension']=data['hypertension'].astype('category')
data['heart_disease']=data['heart_disease'].astype('category')
data['ever_married']=data['ever_married'].astype('category')
data['smoking_status']=data['smoking_status'].astype('category')
data['stroke_ataque_corazon']=data['stroke_ataque_corazon'].astype('category')

data['stroke_ataque_corazon'].value_counts().plot(kind='bar')

#La clase minoritaria tendrá el 50% del tamaño de la clase mayoritaria, adicionando datos sintéticos
from imblearn.over_sampling import SMOTE, SMOTENC

X = data.drop("stroke_ataque_corazon", axis = 1)
Y = data['stroke_ataque_corazon']

smote = SMOTENC(k_neighbors=2, categorical_features=[1,2,3,5], sampling_strategy=0.2)
X_smote, y_smote = smote.fit_resample(X,Y)

# Creamos un dataframe con los resultados (X_smote, y_smote)
data  = pd.DataFrame(columns=X_smote.columns.values, data=X_smote)
data['stroke_ataque_corazon']=y_smote
data['stroke_ataque_corazon'].value_counts().plot(kind='bar')

#Normalizacion las variables numéricas (las dummies no se normalizan)
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
variables_numericas=['age','avg_glucose_level']

min_max_scaler.fit(data[variables_numericas]) #Ajuste de los parametros: max - min
data[variables_numericas]= min_max_scaler.transform(data[variables_numericas]) #70%
data.head()

#Dummies para las variables predictoras
data = pd.get_dummies(data, columns=['smoking_status'], drop_first=False, dtype=int)
data = pd.get_dummies(data, columns=['hypertension','heart_disease','ever_married',], drop_first=True, dtype=int)

data.head()

#LabelEncoder para la variable objetivo
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data["stroke_ataque_corazon"]=labelencoder.fit_transform(data["stroke_ataque_corazon"])
data.head()

"""# **2. División de Datos**"""

#División 70-30
from sklearn.model_selection import train_test_split
X = data.drop("stroke_ataque_corazon", axis = 1)
Y = data['stroke_ataque_corazon']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y)

"""# **3. Clasificadores individuales - débiles (base learners)**"""

#Arbol de clasificación
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier(criterion='gini', min_samples_leaf=20, max_depth=5)
model_dt.fit(X_train, Y_train)

#Evaluación
from sklearn import metrics
Y_pred = model_dt.predict(X_test)
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

from sklearn.tree import plot_tree
plt.figure(figsize=(20,20))
plot_tree(model_dt, feature_names=X_train.columns.values, class_names=labelencoder.classes_, rounded=True, filled=True)
plt.show()

#Método Perezoso
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=1, metric='euclidean')
model_knn.fit(X_train, Y_train)

#Evaluación
Y_pred = model_knn.predict(X_test)
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

#Red neuronal
from sklearn.neural_network import MLPClassifier
model_rn = MLPClassifier(activation="relu",hidden_layer_sizes=(25), learning_rate='constant',
                     learning_rate_init=0.02, momentum= 0.3, max_iter=500, verbose=False)
model_rn.fit(X_train, Y_train)

#Evaluación
Y_pred = model_rn.predict(X_test)
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

"""# 4. Bagging"""

#Bagging: Knn
from sklearn.ensemble import BaggingClassifier #BaggingRegressor
modelo_base=KNeighborsClassifier(n_neighbors=1, metric='euclidean')

model_bag = BaggingClassifier(modelo_base, n_estimators=100, max_samples=0.6) #n_estimators=100
model_bag.fit(X_train, Y_train)#70%

#Evaluación
Y_pred = model_bag.predict(X_test) #30%
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

"""# 5. Random Forest (bagging)"""

#Random Forest
from sklearn.ensemble import RandomForestClassifier
model_rf= RandomForestClassifier(n_estimators=100,  max_samples=0.7, criterion='gini',
                              max_depth=None, min_samples_leaf=2)
model_rf.fit(X_train, Y_train) #70%


#Evaluación
Y_pred = model_rf.predict(X_test) #30%
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

# Se imprimen la importancia de las características
print('Importancia de las características')
for i, j in sorted(zip(X_train.columns, model_rf.feature_importances_)):
    print(i, j)

"""# 6. Boosting"""

#AdaBoost:Adaptive Boosting - Cada modelo siguiente se enfoca en los errores del anterior
from sklearn.ensemble import AdaBoostClassifier


modelo_base=DecisionTreeClassifier(criterion='gini', min_samples_leaf=2)

model_boos = AdaBoostClassifier(modelo_base, n_estimators=50)
model_boos.fit(X_train, Y_train)#70%

#Evaluación
Y_pred = model_boos.predict(X_test)#30%
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

# Gradient Boosting: utiliza gradiente descendente para ajustar los árboles en la dirección que reduce el error.


from sklearn.ensemble import GradientBoostingClassifier

#tasa de aprendizaje controla el tamaño de la actualización de cada modelo
model_gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, subsample=0.8,  min_samples_leaf=2, max_depth=10)
model_gbc.fit(X_train, Y_train) #70%


#Evaluación
Y_pred = model_gbc.predict(X_test) #30%
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

# XGboost: Optimización extrema de Gradient Boosting.
# Procesamiento en paralelo, regularización, maneja valores faltantes
import xgboost as xgb


model_xgb = xgb.XGBClassifier(
    max_depth=10,
    learning_rate=0.1,
    n_estimators=100,
    subsample=0.8  #enable_categorical=True,
)

model_xgb.fit(X_train, Y_train) #70%

#Evaluación
Y_pred = model_xgb.predict(X_test) #30%
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

!pip install catboost

#CatBoostClassifier: especial para variables categóricas, sin crear dummies

from catboost import CatBoostClassifier

model_cat= CatBoostClassifier(iterations= 100,depth= 10, verbose= False,
                              cat_features=[]) #Variables categóricas
model_cat.fit(X_train, Y_train)


#Evaluación
Y_pred = model_cat.predict(X_test) #30%
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

"""# 7. Votación "hard"
"""

#Votación hard: todos los modelos tiene el mismo peso
from sklearn.ensemble import VotingClassifier

clasificadores= [('dt', model_dt), ('knn', model_knn), ('net', model_rn)]

model_vot_hard = VotingClassifier(estimators=clasificadores, voting='hard')
model_vot_hard.fit(X_train,Y_train) #70%

#Evaluación
Y_pred = model_vot_hard.predict(X_test)#30%
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

"""# 8. Votación "soft"
"""

#Votación soft

from sklearn.ensemble import VotingClassifier

clasificadores= [('dt', model_dt), ('knn', model_knn), ('net', model_rn)]
model_vot_soft = VotingClassifier(estimators=clasificadores, voting='soft', weights=[0.3, 0.4, 0.3])
model_vot_soft.fit(X_train,Y_train) #70%

#Evaluación
Y_pred = model_vot_soft.predict(X_test) #30%
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

"""# 9. Stacking"""

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

clasificadores= [('dt', model_dt), ('knn', model_knn), ('net', model)] # RF, XgBoost

metodo_ensamblador= LogisticRegression() #SVM, NN, KNN, RF, XgBoost


model_stack= StackingClassifier(estimators=clasificadores, final_estimator=metodo_ensamblador)
model_stack.fit(X_train,Y_train)#70%

#Evaluación
Y_pred = model_stack.predict(X_test) #30%
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

#Mi stacking
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

clasificadores= [('XgBoost', model_xgb), ('knn', model_knn), ('Adaboost', model_boos)] # RF, XgBoost

metodo_ensamblador= KNeighborsClassifier() #SVM, NN, KNN, RF, XgBoost


model_stack= StackingClassifier(estimators=clasificadores, final_estimator=metodo_ensamblador)
model_stack.fit(X_train,Y_train)#70%

#Evaluación
Y_pred = model_stack.predict(X_test) #30%
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=labelencoder.classes_))

"""# **10.Guardar el mejor modelo**"""

import pickle
filename = 'modelo-ensamble-clas.pkl'
variables=X.columns._values
pickle.dump([model_stack,variables, labelencoder, min_max_scaler], open(filename, 'wb'))