# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqY-7h0ZqOUFrHjU9DJeGK2_Fb2E6ZPB

# **Despliegue**

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-ensamble-clas.pkl'
modelo, variables, labelencoder, min_max_scaler = pickle.load(open(filename, 'rb'))

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de Riesgo de Ataque al Corazón')

Age = st.slider('Edad', min_value=1, max_value=90, value=40, step=1)
Hypertension = st.selectbox('Hipertensión', ['No', 'Yes'])
HeartDisease = st.selectbox('Enfermedad Cardíaca', ['No', 'Yes'])
EverMarried = st.selectbox('Alguna vez casado/a', ['No', 'Yes'])
AvgGlucoseLevel = st.slider('Nivel Promedio de Glucosa', min_value=50.0, max_value=300.0, value=100.0, step=0.1)
SmokingStatus = st.selectbox('Estado de Tabaquismo', ['Unknown', "'never smoked'", "'formerly smoked'", "smokes"])


#Dataframe
datos = [[Age, Hypertension, HeartDisease, EverMarried, AvgGlucoseLevel, SmokingStatus]]
data_raw_input = pd.DataFrame(datos, columns=['age', 'hypertension', 'heart_disease', 'ever_married', 'avg_glucose_level', 'smoking_status'])

#Se realiza la preparación
data_preparada = data_raw_input.copy()

# Apply one-hot encoding for smoking_status (drop_first=False)
data_preparada = pd.get_dummies(data_preparada, columns=['smoking_status'], drop_first=False, dtype=int)

# Apply one-hot encoding for the rest (drop_first=True)
data_preparada = pd.get_dummies(data_preparada, columns=['hypertension','heart_disease','ever_married'], drop_first=True, dtype=int)

# Identify numerical features for scaling (from original notebook)
numeric_features = ['age', 'avg_glucose_level']

# Se adicionan las columnas faltantes y se reordena para que coincidan con las variables de entrenamiento
# Esto es crucial para que el modelo reciba las características en el mismo orden y formato
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)

#Se normaliza las variables numéricas
data_preparada[numeric_features] = min_max_scaler.transform(data_preparada[numeric_features])


"""# **Predicciones**"""

Y_pred_numeric = modelo.predict(data_preparada)
Y_pred_label = labelencoder.inverse_transform(Y_pred_numeric)

data_raw_input['Prediccion'] = Y_pred_label
st.write(data_raw_input) # Display the input data with prediction

st.success(f"La predicción es: {Y_pred_label[0]}")
